#!/usr/bin/env bash
# init-index.sh
# Purpose: Initialize index.yaml skeleton

set -euo pipefail

# Script metadata
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Usage
usage() {
  cat << EOF
Usage: $0 <project-root>

Initialize .spec-drive/index.yaml with empty skeleton.

Arguments:
  project-root    Path to the project

Example:
  $0 /path/to/my-project
EOF
}

# Validate arguments
if [ $# -ne 1 ]; then
  usage >&2
  exit 1
fi

PROJECT_ROOT="$1"

# Validate project root exists
if [ ! -d "$PROJECT_ROOT" ]; then
  echo "❌ ERROR: Project root does not exist: $PROJECT_ROOT" >&2
  exit 1
fi

SPEC_DRIVE_DIR="$PROJECT_ROOT/.spec-drive"
INDEX_FILE="$SPEC_DRIVE_DIR/index.yaml"
CONFIG_FILE="$SPEC_DRIVE_DIR/config.yaml"

# Ensure .spec-drive and config.yaml exist
if [ ! -d "$SPEC_DRIVE_DIR" ]; then
  echo "❌ ERROR: .spec-drive/ not found. Run init-directories.sh first." >&2
  exit 1
fi

if [ ! -f "$CONFIG_FILE" ]; then
  echo "❌ ERROR: config.yaml not found. Run generate-config.sh first." >&2
  exit 1
fi

echo "================================================"
echo "  Initializing index.yaml"
echo "================================================"
echo "Project: $PROJECT_ROOT"
echo ""

# Read project name from config
if command -v yq &> /dev/null; then
  PROJECT_NAME=$(yq eval '.project.name' "$CONFIG_FILE" 2>/dev/null || echo "unknown-project")
else
  # Fallback: simple grep-based extraction
  PROJECT_NAME=$(grep "^  name:" "$CONFIG_FILE" | sed 's/.*: *"\?\([^"]*\)"\?/\1/' || echo "unknown-project")
fi

echo "  📝 PROJECT_NAME: $PROJECT_NAME"
echo ""

# Check if index.yaml already exists
if [ -f "$INDEX_FILE" ]; then
  echo "⚠️  WARNING: index.yaml already exists"
  read -p "Overwrite? (y/N): " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "❌ Aborted"
    exit 1
  fi
  # Backup existing index
  cp "$INDEX_FILE" "$INDEX_FILE.bak"
  echo "  📦 Backed up to index.yaml.bak"
fi

# Generate index.yaml
echo "📝 Generating index.yaml..."

cat > "$INDEX_FILE" << EOF
# .spec-drive/index.yaml
# AI-optimized documentation index
# This file is gitignored and regenerated by autodocs system

# Metadata
meta:
  generated: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  version: "0.1.0"
  project_name: "$PROJECT_NAME"

# Component catalog (auto-populated by code analysis)
components: []
# Example:
# - id: "auth-service"
#   type: "service"
#   path: "src/auth/AuthService.ts:15"
#   summary: "Handles user authentication"
#   dependencies: ["database-client"]

# Spec registry (auto-populated from .spec-drive/specs/)
specs: []
# Example:
# - id: "AUTH-001"
#   title: "User authentication"
#   status: "implemented"
#   trace:
#     code:
#       - "src/auth/login.ts:42"
#     tests:
#       - "tests/auth/login.test.ts:12"
#     docs:
#       - "docs/60-features/AUTH-001.md"

# Documentation catalog (auto-populated from docs/)
docs: []
# Example:
# - path: "docs/10-architecture/ARCHITECTURE.md"
#   type: "architecture"
#   summary: "System architecture overview"
#   last_updated: "2025-01-01T12:00:00Z"

# Code catalog (auto-populated from src/)
code: []
# Example:
# - path: "src/auth/login.ts"
#   components: ["auth-service"]
#   specs: ["AUTH-001"]
#   summary: "Login implementation"

# Notes:
# - This file is regenerated by 'index-docs.js'
# - Manual edits will be overwritten
# - Used by Claude Code for efficient context queries
EOF

echo "  ✅ Created $INDEX_FILE"

# Validate YAML syntax
if command -v yq &> /dev/null; then
  echo "✅ Validating YAML syntax..."
  if yq eval '.' "$INDEX_FILE" > /dev/null 2>&1; then
    echo "  ✅ index.yaml is valid YAML"
  else
    echo "  ❌ index.yaml has syntax errors" >&2
    exit 1
  fi
fi

echo ""
echo "================================================"
echo "  index.yaml initialized successfully!"
echo "================================================"
echo ""
echo "Note: index.yaml is gitignored (regenerable)"
echo "To populate with actual data, run: scripts/tools/index-docs.js"
echo ""

exit 0
