#!/usr/bin/env bash
# init-directories.sh
# Purpose: Initialize .spec-drive/ directory structure in user project

set -euo pipefail

# Script metadata
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PLUGIN_ROOT="${CLAUDE_PLUGIN_ROOT:-$(cd "$SCRIPT_DIR/../.." && pwd)}"

# Usage
usage() {
  cat << EOF
Usage: $0 <project-root>

Initialize .spec-drive/ directory structure for a project.

Arguments:
  project-root    Path to the project where .spec-drive/ should be created

Example:
  $0 /path/to/my-project
EOF
}

# Validate arguments
if [ $# -ne 1 ]; then
  usage >&2
  exit 1
fi

PROJECT_ROOT="$1"

# Validate project root exists
if [ ! -d "$PROJECT_ROOT" ]; then
  echo "❌ ERROR: Project root does not exist: $PROJECT_ROOT" >&2
  exit 1
fi

SPEC_DRIVE_DIR="$PROJECT_ROOT/.spec-drive"

echo "================================================"
echo "  Initializing .spec-drive/ structure"
echo "================================================"
echo "Project: $PROJECT_ROOT"
echo ""

# Check if .spec-drive already exists
if [ -d "$SPEC_DRIVE_DIR" ]; then
  echo "⚠️  WARNING: .spec-drive/ already exists"
  read -p "Overwrite? (y/N): " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "❌ Aborted"
    exit 1
  fi
  echo "Removing existing .spec-drive/"
  rm -rf "$SPEC_DRIVE_DIR"
fi

# Create main .spec-drive directory
echo "📁 Creating .spec-drive/"
mkdir -p "$SPEC_DRIVE_DIR"

# Create subdirectories
echo "📁 Creating .spec-drive/specs/"
mkdir -p "$SPEC_DRIVE_DIR/specs"

echo "📁 Creating .spec-drive/schemas/v0.1/"
mkdir -p "$SPEC_DRIVE_DIR/schemas/v0.1"

echo "📁 Creating .spec-drive/development/"
mkdir -p "$SPEC_DRIVE_DIR/development"
mkdir -p "$SPEC_DRIVE_DIR/development/current"
mkdir -p "$SPEC_DRIVE_DIR/development/planned"
mkdir -p "$SPEC_DRIVE_DIR/development/completed"
mkdir -p "$SPEC_DRIVE_DIR/development/archive"

echo "📁 Creating .spec-drive/logs/"
mkdir -p "$SPEC_DRIVE_DIR/logs"

# Copy schemas from plugin
echo "📋 Copying schemas from plugin..."
if [ -d "$PLUGIN_ROOT/.spec-drive/schemas/v0.1" ]; then
  cp "$PLUGIN_ROOT/.spec-drive/schemas/v0.1"/*.json "$SPEC_DRIVE_DIR/schemas/v0.1/" || true
  echo "  ✅ Copied $(ls -1 "$SPEC_DRIVE_DIR/schemas/v0.1"/*.json 2>/dev/null | wc -l) schemas"
else
  echo "  ⚠️  WARNING: Plugin schemas not found at $PLUGIN_ROOT/.spec-drive/schemas/v0.1"
fi

# Create README in .spec-drive
cat > "$SPEC_DRIVE_DIR/README.md" << 'EOF'
# .spec-drive/ Directory

This directory contains spec-drive plugin infrastructure.

## Structure

```
.spec-drive/
├── config.yaml          # Project configuration (git tracked)
├── state.yaml           # Runtime state (gitignored)
├── index.yaml           # Documentation index (gitignored)
├── specs/               # Spec YAML files (git tracked)
├── schemas/v0.1/        # JSON Schemas for validation (git tracked)
├── development/         # Planning docs (git tracked)
│   ├── current/         # Active version docs
│   ├── planned/         # Future versions
│   ├── completed/       # Shipped versions
│   └── archive/         # Deprecated docs
└── logs/                # Runtime logs (gitignored)
```

## Files

- **config.yaml**: Project settings, behavior mode, workflow configuration
- **state.yaml**: Current workflow state, dirty flags, runtime data
- **index.yaml**: AI-optimized index mapping specs → code → tests → docs
- **specs/*.yaml**: Feature specifications with acceptance criteria

## Git Tracking

**Tracked** (committed to git):
- config.yaml
- specs/
- schemas/
- development/

**Gitignored** (runtime only):
- state.yaml
- index.yaml
- logs/

🤖 Generated by spec-drive
EOF

echo "  ✅ Created .spec-drive/README.md"

# Create .gitignore for .spec-drive
cat > "$SPEC_DRIVE_DIR/.gitignore" << 'EOF'
# Runtime state (ephemeral)
state.yaml

# Generated index (regenerable)
index.yaml

# Logs (runtime only)
logs/

# Temp files
*.tmp
*.bak
EOF

echo "  ✅ Created .spec-drive/.gitignore"

# Update project .gitignore (if exists)
PROJECT_GITIGNORE="$PROJECT_ROOT/.gitignore"
if [ -f "$PROJECT_GITIGNORE" ]; then
  if ! grep -q ".spec-drive/state.yaml" "$PROJECT_GITIGNORE"; then
    echo "" >> "$PROJECT_GITIGNORE"
    echo "# spec-drive runtime files" >> "$PROJECT_GITIGNORE"
    echo ".spec-drive/state.yaml" >> "$PROJECT_GITIGNORE"
    echo ".spec-drive/index.yaml" >> "$PROJECT_GITIGNORE"
    echo ".spec-drive/logs/" >> "$PROJECT_GITIGNORE"
    echo "  ✅ Updated $PROJECT_ROOT/.gitignore"
  fi
else
  echo "  ℹ️  No .gitignore found (skipping)"
fi

echo ""
echo "================================================"
echo "  .spec-drive/ structure created successfully!"
echo "================================================"
echo ""
echo "Next steps:"
echo "  1. Run init-config.sh to create config.yaml"
echo "  2. Run init-state.sh to create state.yaml"
echo "  3. Run init-index.sh to create index.yaml"
echo ""

exit 0
