#!/usr/bin/env bash
# planning-session.sh
# Purpose: Non-interactive planning session for app-new workflow
# Usage: ./planning-session.sh --name <name> --vision <vision> --features <features> --users <users> --stack <stack>

set -euo pipefail

# Constants
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SPEC_DRIVE_DIR="${SPEC_DRIVE_DIR:-.spec-drive}"
SPECS_DIR="$SPEC_DRIVE_DIR/specs"
INDEX_FILE="$SPEC_DRIVE_DIR/SPECS-INDEX.yaml"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Parse arguments
PROJECT_NAME=""
PROJECT_VISION=""
KEY_FEATURES_RAW=""
TARGET_USERS=""
TECH_STACK=""

while [[ $# -gt 0 ]]; do
  case $1 in
    --name)
      PROJECT_NAME="$2"
      shift 2
      ;;
    --vision)
      PROJECT_VISION="$2"
      shift 2
      ;;
    --features)
      KEY_FEATURES_RAW="$2"
      shift 2
      ;;
    --users)
      TARGET_USERS="$2"
      shift 2
      ;;
    --stack)
      TECH_STACK="$2"
      shift 2
      ;;
    *)
      echo -e "${RED}❌ ERROR: Unknown argument: $1${NC}" >&2
      exit 1
      ;;
  esac
done

# Validate required arguments
if [[ -z "$PROJECT_NAME" ]] || [[ -z "$PROJECT_VISION" ]] || [[ -z "$KEY_FEATURES_RAW" ]] || [[ -z "$TARGET_USERS" ]] || [[ -z "$TECH_STACK" ]]; then
  echo -e "${RED}❌ ERROR: All arguments are required${NC}" >&2
  echo "Usage: $0 --name <name> --vision <vision> --features <features> --users <users> --stack <stack>" >&2
  exit 1
fi

# Parse pipe-separated features into array
IFS='|' read -ra KEY_FEATURES <<< "$KEY_FEATURES_RAW"

# Validate at least one feature
if [[ ${#KEY_FEATURES[@]} -eq 0 ]]; then
  echo -e "${RED}❌ ERROR: At least one feature is required${NC}" >&2
  exit 1
fi

echo -e "${BLUE}📋 Planning Session${NC}"
echo "Creating APP-001 spec with provided information..."
echo ""

# ==============================================================================
# Generate APP-001 Spec
# ==============================================================================

echo -e "${BLUE}Generating APP-001 spec...${NC}"

# Create specs directory if it doesn't exist
mkdir -p "$SPECS_DIR"

# Generate timestamp
TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)

# Build key features YAML array
FEATURES_YAML=""
for feature in "${KEY_FEATURES[@]}"; do
  FEATURES_YAML+="  - \"$feature\"\n"
done

# Create APP-001 spec
cat > "$SPECS_DIR/APP-001.yaml" << EOF
# APP-001: $PROJECT_NAME Project Specification
# Auto-generated by app-new workflow

spec_id: APP-001
title: "$PROJECT_NAME Project"
type: application
status: draft
priority: critical
created: $TIMESTAMP
updated: $TIMESTAMP

description: |
  $PROJECT_VISION

planning:
  vision: |
    $PROJECT_VISION

  key_features:
$(echo -e "$FEATURES_YAML")

  target_users: |
    $TARGET_USERS

  tech_stack: |
    $TECH_STACK

acceptance_criteria: []

dependencies: []

related_specs: []

traces:
  code: []
  tests: []
  docs: []

notes: |
  This spec was created during the app-new planning session.
  Use /spec-drive:feature to start implementing features.
EOF

echo -e "${GREEN}✓${NC} Created APP-001 spec"

# ==============================================================================
# Create Development Structure for APP-001
# ==============================================================================

echo -e "${BLUE}Creating development structure...${NC}"

DEV_APP_DIR="$SPEC_DRIVE_DIR/development/current/APP-001"
mkdir -p "$DEV_APP_DIR/tasks"
mkdir -p "$DEV_APP_DIR/adr"

# Copy planning templates if available
TEMPLATES_DIR="$SPEC_DRIVE_DIR/templates/planning"
if [[ -d "$TEMPLATES_DIR" ]]; then
  # Copy PRD template
  if [[ -f "$TEMPLATES_DIR/PRD-TEMPLATE.md" ]]; then
    cp "$TEMPLATES_DIR/PRD-TEMPLATE.md" "$DEV_APP_DIR/PRD.md"
    # Replace placeholders
    sed -i "s/{{SPEC_ID}}/APP-001/g" "$DEV_APP_DIR/PRD.md" 2>/dev/null || true
    sed -i "s/{{TITLE}}/$PROJECT_NAME Project/g" "$DEV_APP_DIR/PRD.md" 2>/dev/null || true
    echo -e "${GREEN}✓${NC} Created: $DEV_APP_DIR/PRD.md"
  fi

  # Copy TDD template
  if [[ -f "$TEMPLATES_DIR/TDD-TEMPLATE.md" ]]; then
    cp "$TEMPLATES_DIR/TDD-TEMPLATE.md" "$DEV_APP_DIR/TDD.md"
    sed -i "s/{{SPEC_ID}}/APP-001/g" "$DEV_APP_DIR/TDD.md" 2>/dev/null || true
    sed -i "s/{{TITLE}}/$PROJECT_NAME Project/g" "$DEV_APP_DIR/TDD.md" 2>/dev/null || true
    echo -e "${GREEN}✓${NC} Created: $DEV_APP_DIR/TDD.md"
  fi

  # Copy TASK template to tasks/
  if [[ -f "$TEMPLATES_DIR/TASK-TEMPLATE.md" ]]; then
    cp "$TEMPLATES_DIR/TASK-TEMPLATE.md" "$DEV_APP_DIR/tasks/README.md"
    echo -e "${GREEN}✓${NC} Created: $DEV_APP_DIR/tasks/README.md"
  fi
fi

echo -e "${GREEN}✓${NC} Development structure created"

# ==============================================================================
# Update SPECS-INDEX.yaml
# ==============================================================================

echo -e "${BLUE}Updating SPECS-INDEX...${NC}"

# Create index if it doesn't exist
if [[ ! -f "$INDEX_FILE" ]]; then
  cat > "$INDEX_FILE" << EOF
# SPECS-INDEX.yaml
# Master index of all specifications

version: "0.1"
updated: $TIMESTAMP

specs:
  - spec_id: APP-001
    title: "$PROJECT_NAME Project"
    type: application
    status: draft
    file: specs/APP-001.yaml
    created: $TIMESTAMP

docs: []

meta:
  total_specs: 1
  total_docs: 0
EOF
else
  # Update existing index
  yq eval ".updated = \"$TIMESTAMP\" | \
           .specs += [{\"spec_id\": \"APP-001\", \"title\": \"$PROJECT_NAME Project\", \"type\": \"application\", \"status\": \"draft\", \"file\": \"specs/APP-001.yaml\", \"created\": \"$TIMESTAMP\"}] | \
           .meta.total_specs = (.specs | length)" \
    "$INDEX_FILE" -i
fi

echo -e "${GREEN}✓${NC} Updated SPECS-INDEX"

# ==============================================================================
# Summary
# ==============================================================================

echo ""
echo -e "${GREEN}Planning session complete!${NC}"
echo ""
echo -e "${BLUE}Summary:${NC}"
echo "  Project: $PROJECT_NAME"
echo "  Features: ${#KEY_FEATURES[@]}"
echo "  Spec: APP-001"
echo ""
